# Generated by Django 4.1.5 on 2023-04-23 11:49

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=256)),
                ("cout", models.FloatField()),
                ("ancien_cout", models.FloatField()),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to=app.models.get_image_path)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=256)),
                ("cout", models.FloatField()),
                ("ancien_cout", models.FloatField()),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to=app.models.get_image_path)),
                ("slug", models.SlugField(unique=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.categorie",
                    ),
                ),
                ("ingredients", models.ManyToManyField(to="app.ingredient")),
            ],
        ),
    ]
