# Generated by Django 4.1.5 on 2023-04-24 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("VALIDE", "Plat servi"),
                            ("EN_ATTENTE", "En attente"),
                            ("ANNULE", "Commande annulée"),
                        ],
                        max_length=100,
                    ),
                ),
                ("numero_table", models.CharField(max_length=100)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="ancien_cout",
            field=models.DecimalField(decimal_places=2, max_digits=999999999),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="cout",
            field=models.DecimalField(decimal_places=2, max_digits=999999999),
        ),
        migrations.AlterField(
            model_name="item",
            name="ancien_cout",
            field=models.DecimalField(decimal_places=2, max_digits=999999999),
        ),
        migrations.AlterField(
            model_name="item",
            name="cout",
            field=models.DecimalField(decimal_places=2, max_digits=999999999),
        ),
        migrations.CreateModel(
            name="CartOrderItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=200)),
                ("image", models.CharField(max_length=200)),
                ("qty", models.IntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default="1.9", max_digits=9999999
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.cartorder"
                    ),
                ),
            ],
        ),
    ]
