# Generated by Django 4.1.5 on 2023-05-05 12:22

import app.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_itemingredients_alter_item_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartorderitems",
            name="order",
        ),
        migrations.RemoveField(
            model_name="item",
            name="ancien_cout",
        ),
        migrations.AddField(
            model_name="categorie",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="categorie",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to=app.models.get_image_path
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="itemimages",
            name="item",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.item"
            ),
        ),
        migrations.DeleteModel(
            name="CartOrder",
        ),
        migrations.DeleteModel(
            name="CartOrderItems",
        ),
    ]
