# Generated by Django 4.1.5 on 2023-05-05 14:09

import app.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_categorie_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorie",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                default="cat.png",
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[300, 120],
                upload_to=app.models.get_image_path,
            ),
        ),
    ]
