# Generated by Django 4.1.5 on 2023-05-05 14:47

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("app", "0009_alter_categorie_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
