# Generated by Django 4.1.5 on 2023-05-05 15:05

import app.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_item_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format=None,
                keep_meta=True,
                quality=-1,
                scale=None,
                size=[195, 196],
                upload_to=app.models.get_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format=None,
                keep_meta=True,
                quality=-1,
                scale=None,
                size=[195, 196],
                upload_to=app.models.get_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="itemimages",
            name="images",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                default="item.png",
                force_format=None,
                keep_meta=True,
                quality=-1,
                scale=None,
                size=[410, 288],
                upload_to=app.models.get_image_path,
            ),
        ),
    ]
