# Generated by Django 4.1.5 on 2023-05-05 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_alter_ingredient_image_alter_item_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemingredients",
            old_name="Ingredient",
            new_name="ingredient",
        ),
        migrations.AlterField(
            model_name="itemingredients",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="app.item",
            ),
        ),
    ]
