# Generated by Django 4.1.5 on 2023-05-05 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_rename_ingredient_itemingredients_ingredient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemimages",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_images",
                to="app.item",
            ),
        ),
        migrations.AlterField(
            model_name="itemreview",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="item_review",
                to="app.item",
            ),
        ),
    ]
