# Generated by Django 4.1.5 on 2023-05-05 18:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_alter_itemimages_item_alter_itemreview_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemimages",
            old_name="images",
            new_name="image",
        ),
    ]
